Zofia Jankowska

In [1]:
import numpy as np
from keras.datasets import mnist
import keras
from keras import layers
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
training_set, test_set = mnist.load_data()

In [3]:
X_train, y_train = training_set
X_test, y_test = test_set

In [4]:
print(X_train.shape)

(60000, 28, 28)


In [5]:
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)

In [6]:
print(X_train.shape)

(60000, 28, 28, 1)


In [7]:
X_train = X_train.astype(float) / 255.0  
X_test = X_test.astype(float) / 255.0

Przygotowanie eksperymantu

In [8]:
num_classes = 10
input_shape = (28, 28, 1)
batch_size = 128
epochs = 30

In [9]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 10)                7850      
                                                                 
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])


Uczenie modelu

In [12]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 2s 4ms/step - loss: 0.7337 - accuracy: 0.8188 - val_loss: 0.4054 - val_accuracy: 0.8957
Epoch 2/30
375/375 [==============================] - 1s 3ms/step - loss: 0.3877 - accuracy: 0.8971 - val_loss: 0.3335 - val_accuracy: 0.9092
Epoch 3/30
375/375 [==============================] - 1s 3ms/step - loss: 0.3370 - accuracy: 0.9079 - val_loss: 0.3085 - val_accuracy: 0.9168
Epoch 4/30
375/375 [==============================] - 1s 3ms/step - loss: 0.3136 - accuracy: 0.9136 - val_loss: 0.2940 - val_accuracy: 0.9192
Epoch 5/30
375/375 [==============================] - 1s 3ms/step - loss: 0.2998 - accuracy: 0.9169 - val_loss: 0.2836 - val_accuracy: 0.9225
Epoch 6/30
375/375 [==============================] - 1s 3ms/step - loss: 0.2901 - accuracy: 0.9190 - val_loss: 0.2784 - val_accuracy: 0.9222
Epoch 7/30
375/375 [==============================] - 1s 3ms/step - loss: 0.2831 - accuracy: 0.9208 - val_loss: 0.2753 - val_accuracy: 0.9227
Epoch 

Ocena modelu

In [13]:
from sklearn.metrics import classification_report, confusion_matrix

In [14]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

313/313 [==============================] - 1s 2ms/step


In [15]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97       980
           1       0.97      0.98      0.98      1135
           2       0.92      0.91      0.91      1032
           3       0.92      0.91      0.91      1010
           4       0.95      0.92      0.93       982
           5       0.91      0.88      0.89       892
           6       0.93      0.96      0.94       958
           7       0.93      0.93      0.93      1028
           8       0.88      0.89      0.89       974
           9       0.90      0.92      0.91      1009

    accuracy                           0.93     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.93      0.93      0.93     10000

[[ 959    0    1    2    0    6    9    2    1    0]
 [   0 1115    3    2    0    1    4    2    8    0]
 [   3   10  935   13    6    4   13    8   36    4]
 [   3    0   20  915    0   25    3   12   23    9]
 [   1    2    8    1  905   

Sieć MLP

In [16]:
model2 = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(64, activation="tanh"),
            layers.Dense(128, activation="tanh"),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

In [17]:
model2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_1 (Dense)             (None, 64)                50240     
                                                                 
 dense_2 (Dense)             (None, 128)               8320      
                                                                 
 dense_3 (Dense)             (None, 10)                1290      
                                                                 
Total params: 59,850
Trainable params: 59,850
Non-trainable params: 0
_________________________________________________________________


In [18]:
model2.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
model2.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 2s 4ms/step - loss: 0.4060 - accuracy: 0.8847 - val_loss: 0.2300 - val_accuracy: 0.9316
Epoch 2/30
375/375 [==============================] - 2s 6ms/step - loss: 0.1925 - accuracy: 0.9437 - val_loss: 0.1680 - val_accuracy: 0.9513
Epoch 3/30
375/375 [==============================] - 2s 7ms/step - loss: 0.1395 - accuracy: 0.9590 - val_loss: 0.1411 - val_accuracy: 0.9576
Epoch 4/30
375/375 [==============================] - 2s 6ms/step - loss: 0.1094 - accuracy: 0.9672 - val_loss: 0.1231 - val_accuracy: 0.9632
Epoch 5/30
375/375 [==============================] - 2s 5ms/step - loss: 0.0888 - accuracy: 0.9734 - val_loss: 0.1183 - val_accuracy: 0.9638
Epoch 6/30
375/375 [==============================] - 2s 6ms/step - loss: 0.0710 - accuracy: 0.9785 - val_loss: 0.1099 - val_accuracy: 0.9655
Epoch 7/30
375/375 [==============================] - 2s 6ms/step - loss: 0.0602 - accuracy: 0.9817 - val_loss: 0.1029 - val_accuracy: 0.9697
Epoch 

In [19]:
y_probab = model2.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

313/313 [==============================] - 0s 1ms/step


In [20]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.97      0.97      0.97      1032
           3       0.97      0.98      0.97      1010
           4       0.98      0.97      0.98       982
           5       0.97      0.98      0.97       892
           6       0.98      0.98      0.98       958
           7       0.97      0.97      0.97      1028
           8       0.97      0.96      0.97       974
           9       0.98      0.97      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000

[[ 970    1    1    1    1    1    3    0    2    0]
 [   0 1127    1    1    0    1    2    1    2    0]
 [   4    1 1001    4    1    1    2   10    7    1]
 [   0    0    3  989    0    6    0    5    4    3]
 [   0    0    2    1  955   

Sieć konwolucyjna

In [21]:
model3 = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Flatten(),
            layers.Dropout(0.5),
            layers.Dense(num_classes, activation="softmax"),
        ]
    )

In [22]:
model3.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 flatten_2 (Flatten)         (None, 1600)              0         
                                                                 
 dropout (Dropout)           (None, 1600)             

In [23]:
model3.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
model3.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 23s 58ms/step - loss: 0.3997 - accuracy: 0.8785 - val_loss: 0.1010 - val_accuracy: 0.9718
Epoch 2/30
375/375 [==============================] - 26s 69ms/step - loss: 0.1201 - accuracy: 0.9633 - val_loss: 0.0693 - val_accuracy: 0.9811
Epoch 3/30
375/375 [==============================] - 18s 48ms/step - loss: 0.0883 - accuracy: 0.9730 - val_loss: 0.0594 - val_accuracy: 0.9839
Epoch 4/30
375/375 [==============================] - 16s 44ms/step - loss: 0.0742 - accuracy: 0.9767 - val_loss: 0.0500 - val_accuracy: 0.9858
Epoch 5/30
375/375 [==============================] - 22s 59ms/step - loss: 0.0674 - accuracy: 0.9791 - val_loss: 0.0488 - val_accuracy: 0.9862
Epoch 6/30
375/375 [==============================] - 25s 66ms/step - loss: 0.0601 - accuracy: 0.9816 - val_loss: 0.0446 - val_accuracy: 0.9872
Epoch 7/30
375/375 [==============================] - 16s 42ms/step - loss: 0.0552 - accuracy: 0.9828 - val_loss: 0.0422 - val_accuracy:

In [24]:
y_probab = model3.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

313/313 [==============================] - 2s 5ms/step


In [25]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       980
           1       1.00      1.00      1.00      1135
           2       0.99      0.99      0.99      1032
           3       0.99      0.99      0.99      1010
           4       0.99      0.99      0.99       982
           5       0.99      0.99      0.99       892
           6       0.99      0.99      0.99       958
           7       0.99      0.99      0.99      1028
           8       0.99      1.00      0.99       974
           9       0.99      0.99      0.99      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000

[[ 976    0    1    0    1    0    0    1    1    0]
 [   0 1133    2    0    0    0    0    0    0    0]
 [   1    1 1020    0    1    0    2    6    1    0]
 [   0    0    2 1004    0    3    0    0    1    0]
 [   0    0    0    0  974   

Sieć konwolucyjna daje najlepsze wyniki ale czas jej wykonywania trwa bardzo długo. Natomiast sieć MLP ma znacznie krótdszy czas, a wyniki sa tylko nieznacznie gorsze.